Repository artsy/convection, pull requests merged in 2020-06, with the labels that each got.

#670 Library Updates
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green, lib update

#678 Added published_at column to submission (CSGN-165)
  app/services/submission_service.rb
  db/migrate/20200604164331_add_published_at_to_submission.rb
  db/schema.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#679 Add the new published at timestamp to schema
  _schema.graphql
Labels: Merge On Green

#680 Expose an offer query
  _schema.graphql
  app/graphql/resolvers/offer_resolver.rb
  app/graphql/types/query_type.rb
  spec/requests/api/graphql/queries/offer_spec.rb
Labels: Merge On Green

#681 Deploy
  _schema.graphql
  app/graphql/mutations/create_submission_mutation.rb
  app/graphql/resolvers/offer_resolver.rb
  app/graphql/types/query_type.rb
  app/services/submission_service.rb
  db/migrate/20200604164331_add_published_at_to_submission.rb
  db/schema.rb
  package.json
  spec/requests/api/graphql/mutations/create_consignment_submission_spec.rb
  spec/requests/api/graphql/queries/offer_spec.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#685 Library Updates
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green, lib update

#686 Always enable new cops
  .rubocop.yml
Labels: Merge On Green

#696 Manual updates
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green

#706 Refactor page connection
  Gemfile.lock
  app/graphql/types/pagination/pageable_connection.rb
  yarn.lock
Labels: Merge On Green
