Repository artsy/convection, pull requests merged in 2020-05, with the labels that each got.

#608 Be more defensive when returning partner offers
  app/graphql/types/submission_type.rb
  spec/requests/api/graphql/queries/submission_spec.rb
Labels: Merge On Green

#613 Library Updates
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green

#614 Minor improvements to upgrade script
  bin/update
Labels: Merge On Green

#619 [CSGN-153] Update final missing images email
  app/mailers/user_mailer.rb
  app/views/user_mailer/third_upload_reminder.html.erb
  spec/requests/submission_spec.rb
Labels: Merge On Green

#620 Deploy
  app/mailers/user_mailer.rb
  app/views/user_mailer/submission_approved.html.erb
  app/views/user_mailer/submission_rejected.html.erb
  app/views/user_mailer/third_upload_reminder.html.erb
  spec/requests/submission_spec.rb
  spec/services/submission_service_spec.rb
  spec/views/admin/submissions/show.html.erb_spec.rb
Labels: Jira Synced

#624 Library Updates
  Gemfile
  Gemfile.lock
  bin/update
Labels: Merge On Green

#627 Library Updates
  Gemfile
  Gemfile.lock
  yarn.lock
Labels: Merge On Green

#631 Remove the 2nd of 3 reminder emails when submissions lack photos.
  app/assets/stylesheets/emails.css.scss
  app/mailers/user_mailer.rb
  app/services/submission_service.rb
  app/views/user_mailer/second_upload_reminder.html.erb
  app/views/user_mailer/third_upload_reminder.html.erb
  config/initializers/_config.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/requests/submission_spec.rb
  spec/services/submission_service_spec.rb
Labels: Merge On Green

#633 Deploy
  .circleci/config.yml
  app/assets/stylesheets/emails.css.scss
  app/mailers/user_mailer.rb
  app/services/submission_service.rb
  app/views/user_mailer/offer.html.erb
  app/views/user_mailer/second_upload_reminder.html.erb
  app/views/user_mailer/third_upload_reminder.html.erb
  config/initializers/_config.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/requests/submission_spec.rb
  spec/services/offer_service_spec.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#637 Library Updates
  .rubocop.yml
  Gemfile
  Gemfile.lock
  yarn.lock
Labels: Merge On Green

#638 Upgrade Rails
  Gemfile
  Gemfile.lock
  bin/update
Labels: Merge On Green

#649 Library Updates
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green, lib update

#652 Library Updates
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: Merge On Green, lib update

#656 [CSGN-140] Partner can fill in "Sale Location" when making an offer
  app/controllers/admin/offers_controller.rb
  app/graphql/mutations/create_offer_mutation.rb
  app/helpers/offers_helper.rb
  app/views/admin/offers/_auction_consignment.html.erb
  app/views/admin/offers/_auction_consignment_form.html.erb
  db/migrate/20200520221322_add_sale_location_to_offer.rb
  db/schema.rb
  spec/services/offer_service_spec.rb
  spec/views/admin/offers/new_step_1.html.erb_spec.rb
Labels: Merge On Green

#661 Library Updates
  .rubocop.yml
  Gemfile.lock
  bin/schema_check
  package.json
  yarn.lock
Labels: Merge On Green, lib update

#657 Deploy
  .rubocop.yml
  Gemfile.lock
  Rakefile
  _schema.graphql
  app/controllers/admin/offers_controller.rb
  app/graphql/mutations/create_offer_mutation.rb
  app/helpers/offers_helper.rb
  app/views/admin/offers/_auction_consignment.html.erb
  app/views/admin/offers/_auction_consignment_form.html.erb
  bin/schema_check
  db/migrate/20200520221322_add_sale_location_to_offer.rb
  db/schema.rb
  hokusai/ci.sh
  package.json
  spec/services/offer_service_spec.rb
  spec/views/admin/offers/new_step_1.html.erb_spec.rb
  yarn.lock
Labels: Jira Synced

#665 Deploy
  _schema.graphql
  app/graphql/types/offer_type.rb
  spec/requests/api/graphql/queries/submission_spec.rb
Labels: Jira Synced
