Repository artsy/convection, pull requests merged in 2021-11, with the labels that each got.

#1156 fix[SWA-122]: Displaying the correct cataloguer name
  app/views/admin/submissions/_cataloguer.html.erb
Labels: Jira Synced

#1157 Deploy
  app/views/admin/submissions/_cataloguer.html.erb
Labels: Jira Synced

#1166 Deploy
  app/mailers/admin_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/services/offer_service.rb
  app/services/submission_service.rb
  app/services/user_service.rb
  app/views/admin/submissions/_collector_info.html.erb
  app/views/admin_mailer/submission.html.erb
  db/migrate/20211102083208_add_phone_and_name_fields_to_users.rb
  db/schema.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/submissions/update_spec.rb
  spec/requests/api/users/anonymize_user_email_spec.rb
  spec/requests/submission_spec.rb
  spec/services/offer_service_spec.rb
  spec/services/submission_service_spec.rb
  spec/views/admin/offers/show.html.erb_spec.rb
  spec/views/admin/submissions/show.html.erb_spec.rb
Labels: in progress, Jira Synced

#1171 Fix: remove sessionId from submission params
  _schema.graphql
  app/graphql/mutations/create_submission_mutation.rb
  app/graphql/mutations/update_submission_mutation.rb
  app/services/submission_service.rb
  spec/requests/api/graphql/mutations/update_consignment_submission_spec.rb
Labels: Merge On Green

#1170 Deploy
  _schema.graphql
  app/graphql/mutations/create_submission_mutation.rb
  app/graphql/mutations/update_submission_mutation.rb
  app/graphql/resolvers/create_submission_resolver.rb
  app/graphql/resolvers/update_submission_resolver.rb
  app/services/submission_service.rb
  db/migrate/20211116122633_add_session_id_to_user_and_set_gravity_id_nullable.rb
  db/schema.rb
  spec/requests/api/graphql/mutations/create_consignment_submission_spec.rb
  spec/requests/api/graphql/mutations/update_consignment_submission_spec.rb
Labels: Jira Synced

#1167 [Feat]: Replace word consign in user emails
  app/views/shared/email/_email_header.html.erb
  app/views/user_mailer/first_upload_reminder.html.erb
  app/views/user_mailer/other_submission_rejected.erb
  app/views/user_mailer/second_upload_reminder.html.erb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#1180 [Feat]: SWA-100 - Update addAsset mutations
  _schema.graphql
  app/graphql/mutations/add_asset_to_consignment_submission.rb
  app/graphql/mutations/add_assets_to_consignment_submission.rb
  app/graphql/resolvers/add_asset_to_submission_resolver.rb
  app/graphql/resolvers/add_assets_to_submission_resolver.rb
  app/graphql/resolvers/base_resolver.rb
  app/graphql/resolvers/update_submission_resolver.rb
  spec/requests/api/graphql/mutations/add_asset_to_consignment_submission_spec.rb
  spec/requests/submission_spec.rb
Labels: Jira Synced
