Repository artsy/convection, pull requests merged in 2022-03, with the labels that each got.

#1258 Deploy
  app/controllers/concerns/graphql_helper.rb
  app/services/submission_service.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#1261 Deploy
  .rubocop_todo.yml
  _schema.graphql
  app/graphql/extensions/default_value_extension.rb
  app/graphql/extensions/nilable_field_extension.rb
  app/graphql/resolvers/base_resolver.rb
  app/graphql/resolvers/submissions_resolver.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_object.rb
  app/graphql/types/submission_type.rb
  app/models/submission.rb
  spec/requests/api/graphql/extensions/default_value_extension_spec.rb
  spec/requests/api/graphql/extensions/nilable_field_extension_spec.rb
  spec/requests/api/graphql/queries/submissions_spec.rb
Labels: Jira Synced

#1260 feat: update submission receipt email
  app/assets/stylesheets/emails.css.scss
  app/views/user_mailer/artist_submission_rejected.html.erb
  app/views/user_mailer/fake_submission_rejected.html.erb
  app/views/user_mailer/non_target_supply_artist_rejected.html.erb
  app/views/user_mailer/nsv_bsv_submission_rejected.html.erb
  app/views/user_mailer/other_submission_rejected.erb
  app/views/user_mailer/submission_receipt.html.erb
  spec/requests/api/submissions/update_spec.rb
  spec/services/submission_service_spec.rb
  spec/views/admin/submissions/show.html.erb_spec.rb
Labels: Jira Synced

#1263 Deploy
  _schema.graphql
  app/assets/stylesheets/emails.css.scss
  app/graphql/mutations/create_submission_mutation.rb
  app/graphql/types/submission_source_type.rb
  app/models/submission.rb
  app/views/user_mailer/artist_submission_rejected.html.erb
  app/views/user_mailer/fake_submission_rejected.html.erb
  app/views/user_mailer/non_target_supply_artist_rejected.html.erb
  app/views/user_mailer/nsv_bsv_submission_rejected.html.erb
  app/views/user_mailer/other_submission_rejected.erb
  app/views/user_mailer/submission_receipt.html.erb
  db/migrate/20220310110820_add_source_to_submissions.rb
  db/schema.rb
  spec/requests/api/graphql/mutations/create_consignment_submission_spec.rb
  spec/requests/api/submissions/update_spec.rb
  spec/services/submission_service_spec.rb
  spec/views/admin/submissions/show.html.erb_spec.rb
Labels: Jira Synced

#1270 feat: Add myCollectionArtworkID to CreateSubmissionMutation
  _schema.graphql
  app/graphql/mutations/create_submission_mutation.rb
  spec/requests/api/graphql/mutations/create_consignment_submission_spec.rb
Labels: Jira Synced, Squash On Green

#1277 Deploy
  _schema.graphql
  app/graphql/types/state_type.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/submission_receipt.html.erb
  spec/requests/api/graphql/queries/submissions_spec.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#1275 feat: Set artwork submission ID when submitting artworks from My Collection
  app/controllers/concerns/graphql_helper.rb
  app/services/submission_service.rb
  spec/services/submission_service_spec.rb
Labels: Jira Synced

#1280 feat: Set import source when creating My Collection artworks
  app/controllers/concerns/graphql_helper.rb
Labels: Jira Synced

#1281 fix: Remove douplicate importSource key
  app/controllers/concerns/graphql_helper.rb
Labels: Squash On Green
